### PR TITLE
added nested field support

### PR DESCRIPTION
**Pull request by noxify**
Solution for #3

### CODE REVIEW

**Comment by Tiim** [comment]
Will this work on nested objects in an array too?
The source plugin [gridsome-source-sanity](https://github.com/sanity-io/gridsome-source-sanity/issues) doesn't currently download the images and the GraphQl queriy for its images look like this:

```gql
query {
  allSanityPage{
    edges {
      node {
        id
        images {
          asset {
            id
            path
            url
          }
        }
      }
    }
  }
}
```
and result in the following Json

```json

  "data": {
    "allSanityPage": {
      "edges": [
        {
          "node": {
            "id": "1ae23b31-f103-4157-8989-97be03518f14",
            "images": [
              {
                "asset": {
                  "id": "image-98f96cac643346f5152229698b96e574a3653aa8-4592x1724-png",
                  "path": "images/xxxxxs27/dev/98f96cac643346f5152229698b96e574a3653aa8-4592x1724.png",
                  "url": "https://cdn.sanity.io/images/xxxxxs27/dev/98f96cac643346f5152229698b96e574a3653aa8-4592x1724.png"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

Could the url be specified by the following string: `images.asset.path`?

**Edit:** I just found out that that wouldn't even be possible this way because the image `asset` type is a reference to a top level type in graphql. Because of this it is possible to just use the following config:
```js
    {
      use: '@noxify/gridsome-plugin-remote-image',
      options: {
        typeName: 'SanityImageAsset',
        sourceField: 'url',
        targetField: 'staticImages',
        targetPath: './src/assets/remoteImages',
      },
    },
```

**Comment by poltimmer** [comment]
Is support for an array of objects possible? For example:

```
{
  reviews: [
    {
      url: http://foo.bar
    },
    {
      url: http://foo.bar
    }
  ]
}
```

**Comment by noxify** [comment]
Hi @poltimmer 

Possible, yes.
But unfortunately I have currently not enough time to work on this.
Also there is a problem with remote sources which needs, if I’m not wrong, some changes in the gridsome core.

Have to block some time to test it. 
But if you want, feel free to extend the current code base with the needed changes for array of objects.

Let me know if you’re interested, then i will send you an repo invite to make changes.

**Comment by travis-r6s** [comment]
@Tiim Incidentally, Sanity uses an Image CDN, so it may be just as easy to use that instead of downloading all the images and transforming them with Gridsome...

**Comment by Tiim** [comment]
@thetre97 That't true. Although there is some kind of ussage cap on the free plan so it might still be useful.
As you can see in my post above I figured it out for sanity so it all worked out :)

**Comment by noxify** [comment]
Added with https://github.com/noxify/gridsome-plugin-remote-image/releases/tag/v1.1.0

**Pull request closed without merging**
